# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dirceu-test-terraform"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "cluster/terraform.tfstate"
    region         = "us-east-1"
  }
}
